spring:
  datasource:
    # 二、嵌入式数据库配置--h2
    url: jdbc:h2:~/testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

    # 二、非嵌入式数据库配置--MySQL
    #driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/jpa?useUnicode=true&useSSL=true
    #username: root
    #password: 123456
  sql:
    init:
      platform: h2
      enabled: true
      continue-on-error: false
      #data-locations: classpath:data.sql
      #schema-locations: classpath:schema.sql
      mode: never

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
