spring:
  datasource:
    platform: h2
    #jdbc:h2:~/testdb 会报错，数据库不会自动创建---已经解决，降低h2版本199-197
    #url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:~/testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    #data: classpath:sql/boot_backend.sql
  h2:
    console:
      enabled: true
  #不存在会自动创建/包括库、表等
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true