spring:
  datasource:
    # 二、非嵌入式数据库配置--MySQL
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa?useUnicode=true&useSSL=true&serverTimezone=GMT%2B8
#    username: ENC(hEc7NPysxK/gIxN1r6iogy/sadZhFkBLLm+gr55CQKC0nBgCSJXEyU9PmsGi1Li3)
#    password: ENC(MaF3AwPysxK/gIxN1r6iogy/sadZhFkBLLm+gr55CQKC0nBgCSJXEyU9PmsGi1Li3)
    username: ENC(h2O/Y/uwexMM5ae43Em3jQ==)
    password: ENC(c6dZJTavLddGsgWYaAtBFE/kQJe9rIwC)
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator