spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  mail:
    host: smtp.qq.com
    username: 1104428690
    password: nrqtxyjmwqfajghd
    port: 465
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
#  mail:
#    password: nrqtxyjmwqfajghd
#    port: 465
#    protocol: smtp
#    host: smtp.qq.com
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true

server:
  port: 8080
logging:
  level:
    pers.xue.batch: info